# Generated by Django 3.1.4 on 2020-12-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20201221_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthplace',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
