# Generated by Django 3.1.4 on 2020-12-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_auto_20201227_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='paintinglink',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
